name: docker build target
description: docker build target and scan image

# NOTE: Fixes "Error: Resource not accessible by integration"
# permissions:
#   contents: read
#   security-events: write

inputs:
  # docker build
  target:
    description: Docker target to build
    required: true

  repository_name:
    description: Repository name
    required: false
    default: ${{ github.event.repository.name }}

  image_tag_suffix:
    description: Suffix to append to the image tag
    required: false
    default: latest

  docker_cli_options:
    description: Additional options to pass to the docker build command
    required: false
    default: "--no-cache"

runs:
  using: composite

  steps:
    - name: "docker build"
      shell: bash
      run: |
        docker build . \
          ${{ inputs.docker_cli_options }} \
          --target ${{ inputs.target }} \
          --tag ${{ inputs.repository_name }}.${{ inputs.target }}:${{ inputs.image_tag_suffix }}
