name: checkout
description: checkout and do some other things
inputs:
  submodules:
    description: whether to update submodules
    required: false
    default: "false"

runs:
  using: composite
  steps:
    # SRC: https://github.com/actions/checkout
    - name: checkout
      uses: actions/checkout@v4

    - name: git submodule update
      if: ${{ inputs.submodules == 'true' }}
      shell: bash
      run: |
        git submodule update --init --recursive
        git submodule update --remote
