#!/bin/bash

set -e

# These variables are mapped 1:1 from variables.tf

echo "TF_VAR_ENVIRONMENT: ${TF_VAR_ENVIRONMENT}"
echo "TF_VAR_ARM_REGION: ${TF_VAR_ARM_REGION}"
echo "TF_VAR_ARM_RESOURCES_PREFIX: ${TF_VAR_ARM_RESOURCES_PREFIX}"
echo "TF_VAR_ARM_RESOURCES_SUFFIX: ${TF_VAR_ARM_RESOURCES_SUFFIX}"
echo "TF_VAR_REPOSITORY_NAME: ${TF_VAR_REPOSITORY_NAME}"

set +e
