"""
This type stub file was generated by pyright.
"""

from typing import Any

def default_cache_key(*args: Any, **kwargs: Any) -> str | bytes:
    """Default cache key function that uses the arguments and keyword arguments to generate a hashable key."""
    ...

