"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any
from langchain_core.callbacks import AsyncCallbackManager, CallbackManager, Callbacks
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.base import CheckpointMetadata

DEFAULT_RECURSION_LIMIT = ...
def recast_checkpoint_ns(ns: str) -> str:
    """Remove task IDs from checkpoint namespace.

    Args:
        ns: The checkpoint namespace with task IDs.

    Returns:
        str: The checkpoint namespace without task IDs.
    """
    ...

def patch_configurable(config: RunnableConfig | None, patch: dict[str, Any]) -> RunnableConfig:
    ...

def patch_checkpoint_map(config: RunnableConfig | None, metadata: CheckpointMetadata | None) -> RunnableConfig:
    ...

def merge_configs(*configs: RunnableConfig | None) -> RunnableConfig:
    """Merge multiple configs into one.

    Args:
        *configs: The configs to merge.

    Returns:
        RunnableConfig: The merged config.
    """
    ...

def patch_config(config: RunnableConfig | None, *, callbacks: Callbacks = ..., recursion_limit: int | None = ..., max_concurrency: int | None = ..., run_name: str | None = ..., configurable: dict[str, Any] | None = ...) -> RunnableConfig:
    """Patch a config with new values.

    Args:
        config: The config to patch.
        callbacks: The callbacks to set.
        recursion_limit: The recursion limit to set.
        max_concurrency: The max number of concurrent steps to run, which also applies to parallelized steps.
        run_name: The run name to set.
        configurable: The configurable to set.

    Returns:
        RunnableConfig: The patched config.
    """
    ...

def get_callback_manager_for_config(config: RunnableConfig, tags: Sequence[str] | None = ...) -> CallbackManager:
    """Get a callback manager for a config.

    Args:
        config: The config.

    Returns:
        CallbackManager: The callback manager.
    """
    ...

def get_async_callback_manager_for_config(config: RunnableConfig, tags: Sequence[str] | None = ...) -> AsyncCallbackManager:
    """Get an async callback manager for a config.

    Args:
        config: The config.

    Returns:
        AsyncCallbackManager: The async callback manager.
    """
    ...

def ensure_config(*configs: RunnableConfig | None) -> RunnableConfig:
    """Return a config with all keys, merging any provided configs.

    Args:
        *configs: Configs to merge before ensuring defaults.

    Returns:
        RunnableConfig: The merged and ensured config.
    """
    ...

_OMIT = ...
