"""
This type stub file was generated by pyright.
"""

import asyncio
import concurrent.futures
import contextvars
from collections.abc import Coroutine
from typing import TypeVar

T = TypeVar("T")
AnyFuture = asyncio.Future | concurrent.futures.Future
CONTEXT_NOT_SUPPORTED = ...
EAGER_NOT_SUPPORTED = ...
def chain_future(source: AnyFuture, destination: AnyFuture) -> AnyFuture:
    ...

def run_coroutine_threadsafe(coro: Coroutine[None, None, T], loop: asyncio.AbstractEventLoop, *, lazy: bool, name: str | None = ..., context: contextvars.Context | None = ...) -> asyncio.Future[T]:
    """Submit a coroutine object to a given event loop.

    Return an asyncio.Future to access the result.
    """
    ...

