"""
This type stub file was generated by pyright.
"""

import dataclasses
from collections.abc import Callable
from typing import Any
from langgraph.types import _DC_KWARGS

@dataclasses.dataclass(**_DC_KWARGS)
class PregelScratchpad:
    step: int
    stop: int
    call_counter: Callable[[], int]
    interrupt_counter: Callable[[], int]
    get_null_resume: Callable[[bool], Any]
    resume: list[Any]
    subgraph_counter: Callable[[], int]
    ...


