"""
This type stub file was generated by pyright.
"""

from typing_extensions import TypeVar
from langgraph._internal._typing import StateLike

__all__ = ("StateT", "StateT_co", "StateT_contra", "InputT", "OutputT", "ContextT")
StateT = TypeVar("StateT", bound=StateLike)
StateT_co = TypeVar("StateT_co", bound=StateLike, covariant=True)
StateT_contra = TypeVar("StateT_contra", bound=StateLike, contravariant=True)
ContextT = TypeVar("ContextT", bound=StateLike | None, default=None)
ContextT_contra = TypeVar("ContextT_contra", bound=StateLike | None, contravariant=True, default=None)
InputT = TypeVar("InputT", bound=StateLike, default=StateT)
OutputT = TypeVar("OutputT", bound=StateLike, default=StateT)
NodeInputT = TypeVar("NodeInputT", bound=StateLike)
NodeInputT_contra = TypeVar("NodeInputT_contra", bound=StateLike, contravariant=True)
