"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any, Generic
from typing_extensions import Self
from langgraph.channels.base import BaseChannel, Value

__all__ = ("Topic", )
class Topic(Generic[Value], BaseChannel[Sequence[Value], Value | list[Value], list[Value]]):
    """A configurable PubSub Topic.

    Args:
        typ: The type of the value stored in the channel.
        accumulate: Whether to accumulate values across steps. If `False`, the channel will be emptied after each step.
    """
    __slots__ = ...
    def __init__(self, typ: type[Value], accumulate: bool = ...) -> None:
        ...
    
    def __eq__(self, value: object) -> bool:
        ...
    
    @property
    def ValueType(self) -> Any:
        """The type of the value stored in the channel."""
        ...
    
    @property
    def UpdateType(self) -> Any:
        """The type of the update received by the channel."""
        ...
    
    def copy(self) -> Self:
        """Return a copy of the channel."""
        ...
    
    def checkpoint(self) -> list[Value]:
        ...
    
    def from_checkpoint(self, checkpoint: list[Value]) -> Self:
        ...
    
    def update(self, values: Sequence[Value | list[Value]]) -> bool:
        ...
    
    def get(self) -> Sequence[Value]:
        ...
    
    def is_available(self) -> bool:
        ...
    


