"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any, Generic
from typing_extensions import Self
from langgraph.channels.base import BaseChannel, Value

__all__ = ("UntrackedValue", )
class UntrackedValue(Generic[Value], BaseChannel[Value, Value, Value]):
    """Stores the last value received, never checkpointed."""
    __slots__ = ...
    guard: bool
    value: Value | Any
    def __init__(self, typ: type[Value], guard: bool = ...) -> None:
        ...
    
    def __eq__(self, value: object) -> bool:
        ...
    
    @property
    def ValueType(self) -> type[Value]:
        """The type of the value stored in the channel."""
        ...
    
    @property
    def UpdateType(self) -> type[Value]:
        """The type of the update received by the channel."""
        ...
    
    def copy(self) -> Self:
        """Return a copy of the channel."""
        ...
    
    def checkpoint(self) -> Value | Any:
        ...
    
    def from_checkpoint(self, checkpoint: Value) -> Self:
        ...
    
    def update(self, values: Sequence[Value]) -> bool:
        ...
    
    def get(self) -> Value:
        ...
    
    def is_available(self) -> bool:
        ...
    


