"""
This type stub file was generated by pyright.
"""

import concurrent.futures
from collections.abc import Awaitable, Callable, Generator, Sequence
from typing import Any, Generic, TypeVar
from langchain_core.runnables import Runnable
from typing_extensions import ParamSpec
from langgraph.types import CachePolicy, RetryPolicy

"""Utility to convert a user provided function into a Runnable with a ChannelWrite."""
def identifier(obj: Any, name: str | None = ...) -> str | None:
    """Return the module and name of an object."""
    ...

def get_runnable_for_entrypoint(func: Callable[..., Any]) -> Runnable:
    ...

def get_runnable_for_task(func: Callable[..., Any]) -> Runnable:
    ...

CACHE: dict[tuple[Callable[..., Any], bool], Runnable] = ...
P = ParamSpec("P")
P1 = TypeVar("P1")
T = TypeVar("T")
class SyncAsyncFuture(Generic[T], concurrent.futures.Future[T]):
    def __await__(self) -> Generator[T, None, T]:
        ...
    


def call(func: Callable[P, Awaitable[T]] | Callable[P, T], *args: Any, retry_policy: Sequence[RetryPolicy] | None = ..., cache_policy: CachePolicy | None = ..., **kwargs: Any) -> SyncAsyncFuture[T]:
    ...

