"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from langgraph.checkpoint.base import Checkpoint
from langgraph.channels.base import BaseChannel
from langgraph.managed.base import ManagedValueMapping, ManagedValueSpec

LATEST_VERSION = ...
def empty_checkpoint() -> Checkpoint:
    ...

def create_checkpoint(checkpoint: Checkpoint, channels: Mapping[str, BaseChannel] | None, step: int, *, id: str | None = ..., updated_channels: set[str] | None = ...) -> Checkpoint:
    """Create a checkpoint for the given channels."""
    ...

def channels_from_checkpoint(specs: Mapping[str, BaseChannel | ManagedValueSpec], checkpoint: Checkpoint) -> tuple[Mapping[str, BaseChannel], ManagedValueMapping]:
    """Get channels from a checkpoint."""
    ...

def copy_checkpoint(checkpoint: Checkpoint) -> Checkpoint:
    ...

