"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping, Sequence
from typing import Any, NamedTuple
from langchain_core.runnables.config import RunnableConfig
from langchain_core.runnables.graph import Graph
from langgraph.channels.base import BaseChannel
from langgraph.managed.base import ManagedValueSpec
from langgraph.pregel._read import PregelNode
from langgraph.types import All, Checkpointer

class Edge(NamedTuple):
    source: str
    target: str
    conditional: bool
    data: str | None
    ...


class TriggerEdge(NamedTuple):
    source: str
    conditional: bool
    data: str | None
    ...


def draw_graph(config: RunnableConfig, *, nodes: dict[str, PregelNode], specs: dict[str, BaseChannel | ManagedValueSpec], input_channels: str | Sequence[str], interrupt_after_nodes: All | Sequence[str], interrupt_before_nodes: All | Sequence[str], trigger_to_nodes: Mapping[str, Sequence[str]], checkpointer: Checkpointer, subgraphs: dict[str, Graph], limit: int = ...) -> Graph:
    """Get the graph for this Pregel instance.

    Args:
        config: The configuration to use for the graph.
        subgraphs: The subgraphs to include in the graph.
        checkpointer: The checkpointer to use for the graph.

    Returns:
        The graph for this Pregel instance.
    """
    ...

def add_edge(graph: Graph, source: str, target: str, *, data: Any | None = ..., conditional: bool = ...) -> None:
    """Add an edge to the graph."""
    ...

