"""
This type stub file was generated by pyright.
"""

import asyncio
import concurrent.futures
import threading
import weakref
from collections.abc import AsyncIterator, Awaitable, Callable, Iterable, Iterator, Sequence
from typing import Any, Generic, TypeVar
from langgraph.pregel._algo import Call
from langgraph.pregel._executor import Submit
from langgraph.types import PregelExecutableTask, RetryPolicy

F = TypeVar("F", concurrent.futures.Future, asyncio.Future)
E = TypeVar("E", threading.Event, asyncio.Event)
EXCLUDED_FRAME_FNAMES = ...
SKIP_RERAISE_SET: weakref.WeakSet[concurrent.futures.Future | asyncio.Future] = ...
class FuturesDict(Generic[F, E], dict[F, PregelExecutableTask | None]):
    event: E
    callback: weakref.ref[Callable[[PregelExecutableTask, BaseException | None], None]]
    counter: int
    done: set[F]
    lock: threading.Lock
    def __init__(self, event: E, callback: weakref.ref[Callable[[PregelExecutableTask, BaseException | None], None]], future_type: type[F]) -> None:
        ...
    
    def __setitem__(self, key: F, value: PregelExecutableTask | None) -> None:
        ...
    
    def on_done(self, task: PregelExecutableTask, fut: F) -> None:
        ...
    


class PregelRunner:
    """Responsible for executing a set of Pregel tasks concurrently, committing
    their writes, yielding control to caller when there is output to emit, and
    interrupting other tasks if appropriate."""
    def __init__(self, *, submit: weakref.ref[Submit], put_writes: weakref.ref[Callable[[str, Sequence[tuple[str, Any]]], None]], use_astream: bool = ..., node_finished: Callable[[str], None] | None = ...) -> None:
        ...
    
    def tick(self, tasks: Iterable[PregelExecutableTask], *, reraise: bool = ..., timeout: float | None = ..., retry_policy: Sequence[RetryPolicy] | None = ..., get_waiter: Callable[[], concurrent.futures.Future[None]] | None = ..., schedule_task: Callable[[PregelExecutableTask, int, Call | None], PregelExecutableTask | None,]) -> Iterator[None]:
        ...
    
    async def atick(self, tasks: Iterable[PregelExecutableTask], *, reraise: bool = ..., timeout: float | None = ..., retry_policy: Sequence[RetryPolicy] | None = ..., get_waiter: Callable[[], asyncio.Future[None]] | None = ..., schedule_task: Callable[[PregelExecutableTask, int, Call | None], Awaitable[PregelExecutableTask | None],]) -> AsyncIterator[None]:
        ...
    
    def commit(self, task: PregelExecutableTask, exception: BaseException | None) -> None:
        ...
    


