"""
This type stub file was generated by pyright.
"""

import ast
from collections.abc import Callable
from typing import Any
from langchain_core.runnables import Runnable
from langgraph.checkpoint.base import ChannelVersions
from typing_extensions import override
from langgraph.pregel.protocol import PregelProtocol

def get_new_channel_versions(previous_versions: ChannelVersions, current_versions: ChannelVersions) -> ChannelVersions:
    """Get subset of current_versions that are newer than previous_versions."""
    ...

def find_subgraph_pregel(candidate: Runnable) -> PregelProtocol | None:
    ...

def get_function_nonlocals(func: Callable) -> list[Any]:
    """Get the nonlocal variables accessed by a function.

    Args:
        func: The function to check.

    Returns:
        List[Any]: The nonlocal variables accessed by the function.
    """
    ...

class FunctionNonLocals(ast.NodeVisitor):
    """Get the nonlocal variables accessed of a function."""
    def __init__(self) -> None:
        ...
    
    @override
    def visit_FunctionDef(self, node: ast.FunctionDef) -> Any:
        """Visit a function definition.

        Args:
            node: The node to visit.

        Returns:
            Any: The result of the visit.
        """
        ...
    
    @override
    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> Any:
        """Visit an async function definition.

        Args:
            node: The node to visit.

        Returns:
            Any: The result of the visit.
        """
        ...
    
    @override
    def visit_Lambda(self, node: ast.Lambda) -> Any:
        """Visit a lambda function.

        Args:
            node: The node to visit.

        Returns:
            Any: The result of the visit.
        """
        ...
    


class NonLocals(ast.NodeVisitor):
    """Get nonlocal variables accessed."""
    def __init__(self) -> None:
        ...
    
    @override
    def visit_Name(self, node: ast.Name) -> Any:
        """Visit a name node.

        Args:
            node: The node to visit.

        Returns:
            Any: The result of the visit.
        """
        ...
    
    @override
    def visit_Attribute(self, node: ast.Attribute) -> Any:
        """Visit an attribute node.

        Args:
            node: The node to visit.

        Returns:
            Any: The result of the visit.
        """
        ...
    


def is_xxh3_128_hexdigest(value: str) -> bool:
    """Check if the given string matches the format of xxh3_128_hexdigest."""
    ...

