"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping, Sequence
from typing import Any
from langgraph.channels.base import BaseChannel
from langgraph.managed.base import ManagedValueMapping
from langgraph.pregel._read import PregelNode
from langgraph.types import All

def validate_graph(nodes: Mapping[str, PregelNode], channels: dict[str, BaseChannel], managed: ManagedValueMapping, input_channels: str | Sequence[str], output_channels: str | Sequence[str], stream_channels: str | Sequence[str] | None, interrupt_after_nodes: All | Sequence[str], interrupt_before_nodes: All | Sequence[str]) -> None:
    ...

def validate_keys(keys: str | Sequence[str] | None, channels: Mapping[str, Any]) -> None:
    ...

