"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from collections.abc import AsyncIterator, Callable, Iterator, Sequence
from typing import Any, Generic
from langchain_core.runnables import Runnable, RunnableConfig
from langchain_core.runnables.graph import Graph as DrawableGraph
from typing_extensions import Self
from langgraph.types import All, Command, StateSnapshot, StateUpdate, StreamMode
from langgraph.typing import ContextT, InputT, OutputT, StateT

__all__ = ("PregelProtocol", "StreamProtocol")
class PregelProtocol(Runnable[InputT, Any], Generic[StateT, ContextT, InputT, OutputT]):
    @abstractmethod
    def with_config(self, config: RunnableConfig | None = ..., **kwargs: Any) -> Self:
        ...
    
    @abstractmethod
    def get_graph(self, config: RunnableConfig | None = ..., *, xray: int | bool = ...) -> DrawableGraph:
        ...
    
    @abstractmethod
    async def aget_graph(self, config: RunnableConfig | None = ..., *, xray: int | bool = ...) -> DrawableGraph:
        ...
    
    @abstractmethod
    def get_state(self, config: RunnableConfig, *, subgraphs: bool = ...) -> StateSnapshot:
        ...
    
    @abstractmethod
    async def aget_state(self, config: RunnableConfig, *, subgraphs: bool = ...) -> StateSnapshot:
        ...
    
    @abstractmethod
    def get_state_history(self, config: RunnableConfig, *, filter: dict[str, Any] | None = ..., before: RunnableConfig | None = ..., limit: int | None = ...) -> Iterator[StateSnapshot]:
        ...
    
    @abstractmethod
    def aget_state_history(self, config: RunnableConfig, *, filter: dict[str, Any] | None = ..., before: RunnableConfig | None = ..., limit: int | None = ...) -> AsyncIterator[StateSnapshot]:
        ...
    
    @abstractmethod
    def bulk_update_state(self, config: RunnableConfig, updates: Sequence[Sequence[StateUpdate]]) -> RunnableConfig:
        ...
    
    @abstractmethod
    async def abulk_update_state(self, config: RunnableConfig, updates: Sequence[Sequence[StateUpdate]]) -> RunnableConfig:
        ...
    
    @abstractmethod
    def update_state(self, config: RunnableConfig, values: dict[str, Any] | Any | None, as_node: str | None = ...) -> RunnableConfig:
        ...
    
    @abstractmethod
    async def aupdate_state(self, config: RunnableConfig, values: dict[str, Any] | Any | None, as_node: str | None = ...) -> RunnableConfig:
        ...
    
    @abstractmethod
    def stream(self, input: InputT | Command | None, config: RunnableConfig | None = ..., *, context: ContextT | None = ..., stream_mode: StreamMode | list[StreamMode] | None = ..., interrupt_before: All | Sequence[str] | None = ..., interrupt_after: All | Sequence[str] | None = ..., subgraphs: bool = ...) -> Iterator[dict[str, Any] | Any]:
        ...
    
    @abstractmethod
    def astream(self, input: InputT | Command | None, config: RunnableConfig | None = ..., *, context: ContextT | None = ..., stream_mode: StreamMode | list[StreamMode] | None = ..., interrupt_before: All | Sequence[str] | None = ..., interrupt_after: All | Sequence[str] | None = ..., subgraphs: bool = ...) -> AsyncIterator[dict[str, Any] | Any]:
        ...
    
    @abstractmethod
    def invoke(self, input: InputT | Command | None, config: RunnableConfig | None = ..., *, context: ContextT | None = ..., interrupt_before: All | Sequence[str] | None = ..., interrupt_after: All | Sequence[str] | None = ...) -> dict[str, Any] | Any:
        ...
    
    @abstractmethod
    async def ainvoke(self, input: InputT | Command | None, config: RunnableConfig | None = ..., *, context: ContextT | None = ..., interrupt_before: All | Sequence[str] | None = ..., interrupt_after: All | Sequence[str] | None = ...) -> dict[str, Any] | Any:
        ...
    


StreamChunk = tuple[tuple[str, ...], str, Any]
class StreamProtocol:
    __slots__ = ...
    modes: set[StreamMode]
    __call__: Callable[[Self, StreamChunk], None]
    def __init__(self, __call__: Callable[[StreamChunk], None], modes: set[StreamMode]) -> None:
        ...
    


